name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build_site:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Install dependencies
        run: pnpm install

      - name: Build SvelteKit
        run: pnpm run build
        env:
          BASE_PATH: '/ForzaHorizon6Randomiser'

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v5
        with:
          # This is the default output directory for adapter-static
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v5
